version: '2'
services:
  nginx:
    build: ./docker/nginx
    ports:
     - "80:80"
    volumes:
     - ./project:/var/www/html
    networks:
     - typo3net
  php:
    build: ./docker/php
    volumes:
     - ./project:/var/www/html
    networks:
     - typo3net
  mysql:
    build: ./docker/mysql
    ports:
     - "3306:3306"
    volumes:
     - ./docker/mysql/data:/var/lib/mysql
    networks:
     - typo3net
networks:
  typo3net:
    driver: "bridge"
